---
- name: restart apache
  service:
    name: httpd
    state: restarted

- name: reload firewalld
  systemd:
    service: firewalld
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
