- name: install epel package
  yum:
    name:
    - epel-release
    state: present

- name: install python packages
  yum:
    name:
    - python3
    - python-jinja2
    state: present

- name: Install selinux add-ons
  yum:
    name:
    - libsemanage-python
    state: present