- name: Open port 80/tcp
  firewalld:
    port: 80/tcp
    state: enabled
    permanent: yes
  register:
    firewall

- name: Reload firewalld
  systemd:
    service: firewalld
    state: restarted
  when:
    firewall.changed