---
- name: Install httpd
  yum:
    name: httpd
    state: present
  register:
    httpd

- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Opening http port 80
  firewalld:
    port: 80/tcp
    state: enabled
    permanent: yes
    notify: 
      - restart apache
      - reload firewalld
